// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AsignarHabitacion(arg1:string):Promise<string>;

export function DespertarPaciente(arg1:string):Promise<string>;

export function NombreHospital():Promise<string>;

export function ObtenerEstadoHospital():Promise<main.EstadoHospitalDTO>;

export function ObtenerPacientes():Promise<Array<main.PacienteDTO>>;

export function RegistrarAtaque(arg1:string,arg2:string):Promise<string>;
