// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AsignarHabitacion(arg1) {
  return window['go']['main']['App']['AsignarHabitacion'](arg1);
}

export function DespertarPaciente(arg1) {
  return window['go']['main']['App']['DespertarPaciente'](arg1);
}

export function NombreHospital() {
  return window['go']['main']['App']['NombreHospital']();
}

export function ObtenerEstadoHospital() {
  return window['go']['main']['App']['ObtenerEstadoHospital']();
}

export function ObtenerPacientes() {
  return window['go']['main']['App']['ObtenerPacientes']();
}

export function RegistrarAtaque(arg1, arg2) {
  return window['go']['main']['App']['RegistrarAtaque'](arg1, arg2);
}
